FROM node:14
ARG STRIPE_PUBLISHABLE_KEY
WORKDIR /app
COPY [".", "."]
RUN npm install
RUN REACT_APP_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY} GATSBY_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY} npm run build