/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConversationMode,
    ConversationModeFromJSON,
    ConversationModeFromJSONTyped,
    ConversationModeToJSON,
    TimeSpan,
    TimeSpanFromJSON,
    TimeSpanFromJSONTyped,
    TimeSpanToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConfigurationFileOverride
 */
export interface ConfigurationFileOverride {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigurationFileOverride
     */
    dockerComposeYmlFilePaths?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ConfigurationFileOverride
     */
    buildArguments?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationFileOverride
     */
    label?: string | null;
    /**
     * 
     * @type {TimeSpan}
     * @memberof ConfigurationFileOverride
     */
    expiry?: TimeSpan;
    /**
     * 
     * @type {ConversationMode}
     * @memberof ConfigurationFileOverride
     */
    conversationMode?: ConversationMode;
}

export function ConfigurationFileOverrideFromJSON(json: any): ConfigurationFileOverride {
    return ConfigurationFileOverrideFromJSONTyped(json, false);
}

export function ConfigurationFileOverrideFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationFileOverride {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dockerComposeYmlFilePaths': !exists(json, 'dockerComposeYmlFilePaths') ? undefined : json['dockerComposeYmlFilePaths'],
        'buildArguments': !exists(json, 'buildArguments') ? undefined : json['buildArguments'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'expiry': !exists(json, 'expiry') ? undefined : TimeSpanFromJSON(json['expiry']),
        'conversationMode': !exists(json, 'conversationMode') ? undefined : ConversationModeFromJSON(json['conversationMode']),
    };
}

export function ConfigurationFileOverrideToJSON(value?: ConfigurationFileOverride | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dockerComposeYmlFilePaths': value.dockerComposeYmlFilePaths,
        'buildArguments': value.buildArguments,
        'label': value.label,
        'expiry': TimeSpanToJSON(value.expiry),
        'conversationMode': ConversationModeToJSON(value.conversationMode),
    };
}


