/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CouponCodeResponse
 */
export interface CouponCodeResponse {
    /**
     * 
     * @type {string}
     * @memberof CouponCodeResponse
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CouponCodeResponse
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CouponCodeResponse
     */
    amountOffInHundreds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CouponCodeResponse
     */
    amountOffInPercentage?: number | null;
}

export function CouponCodeResponseFromJSON(json: any): CouponCodeResponse {
    return CouponCodeResponseFromJSONTyped(json, false);
}

export function CouponCodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponCodeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'amountOffInHundreds': !exists(json, 'amountOffInHundreds') ? undefined : json['amountOffInHundreds'],
        'amountOffInPercentage': !exists(json, 'amountOffInPercentage') ? undefined : json['amountOffInPercentage'],
    };
}

export function CouponCodeResponseToJSON(value?: CouponCodeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'name': value.name,
        'amountOffInHundreds': value.amountOffInHundreds,
        'amountOffInPercentage': value.amountOffInPercentage,
    };
}


