/* tslint:disable */
/* eslint-disable */
/**
 * General
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstallationRepositoryReferencePayload
 */
export interface InstallationRepositoryReferencePayload {
    /**
     * 
     * @type {number}
     * @memberof InstallationRepositoryReferencePayload
     */
    id?: number;
}

export function InstallationRepositoryReferencePayloadFromJSON(json: any): InstallationRepositoryReferencePayload {
    return InstallationRepositoryReferencePayloadFromJSONTyped(json, false);
}

export function InstallationRepositoryReferencePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallationRepositoryReferencePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function InstallationRepositoryReferencePayloadToJSON(value?: InstallationRepositoryReferencePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


