name: Docker

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:

  deploy-dogger-io:
    name: Deploy dogger-io
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'master')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Dockerfile
        run: |
          docker build . -t dogger-image --build-arg STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY_LIVE }}

      - name: Run container
        run: |
          docker run --name dogger dogger-image

      - name: Copy compiled output to host container
        run: |
          docker cp dogger:/app/public ./public
          cd ./public
          ls -R
          cd ../

      - name: Publish to S3
        run: |
          docker run -v configuration:/root/.aws amazon/aws-cli configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          docker run -v configuration:/root/.aws amazon/aws-cli configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker run -v configuration:/root/.aws -v $(pwd)/public:/aws amazon/aws-cli s3 sync . s3://dogger.io --delete --acl public-read