name: Docker

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:

  deploy-dogger-io:
    name: Deploy dogger-io
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'master')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Dockerfile
        run: |
          docker build . -t dogger-image \
            --build-arg STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY_LIVE }} \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run container
        run: |
          docker run --name dogger dogger-image